module Music.Instrument where 

import Euterpea 

i               = instrument 
inst            = instrument 
insts           = [MusicBox, SynthVoice, Celesta, TubularBells]
round           = undefined 

grandPiano      = i AcousticGrandPiano
brightPiano     = i BrightAcousticPiano
electricPiano   = i ElectricGrandPiano
honky           = i HonkyTonkPiano 
rhodes          = i RhodesPiano
chorused        = i ChorusedPiano
harpsi          = i Harpsichord
celesta         = i Celesta
glocken         = i Glockenspiel
box             = i MusicBox
vibra           = i Vibraphone
marimba         = i Marimba
xylo            = i Xylophone
tubular         = i TubularBells
dulcimer        = i Dulcimer
hammondOrgan    = i HammondOrgan
rockOrgan       = i RockOrgan
percussiveOrgan = i PercussiveOrgan
church          = i ChurchOrgan
reed            = i ReedOrgan
accordion       = i Accordion
harmonica       = i Harmonica
tango           = i TangoAccordion
guitar 1        = i AcousticGuitarNylon
guitar 2        = i AcousticGuitarSteel
guitar 3        = i OverdrivenGuitar
guitar 4        = i DistortionGuitar
guitar 5        = i GuitarHarmonics
guitar _        = error "No such Instruments"
eGuitar 1       = i ElectricGuitarJazz
eGuitar 2       = i ElectricGuitarClean
eGuitar 3       = i ElectricGuitarMuted
eGuitar _       = error "No such Instrumets"
bass 1          = i AcousticBass
bass 2          = i ElectricBassFingered
bass 3          = i ElectricBassPicked
bass 4          = i FretlessBass
bass 5          = i SlapBass1
bass 6          = i SlapBass2
bass 7          = i SynthBass1
bass 8          = i SynthBass2
bass _          = error "No such Instrument"
violin          = i Violin
viola           = i Viola
cello           = i Cello
contrabass      = i Contrabass
harp            = i OrchestralHarp
timpani         = i Timpani
string 1        = i TremoloStrings
string 2        = i PizzicatoStrings
string 3        = i StringEnsemble1
string 4        = i StringEnsemble2
string 5        = i SynthStrings1
string 6        = i SynthStrings2
choirAahs       = i ChoirAahs
voiceOohs       = i VoiceOohs
synth 1         = i SynthVoice
orchestra       = i OrchestraHit
trumpet         = i Trumpet
trombone        = i Trombone
tuba            = i Tuba
mutedTrumpet    = i MutedTrumpet
horn 1          = i FrenchHorn
horn 2          = i EnglishHorn
brass 1         = i BrassSection
brass 2         = i SynthBrass1
brass 3         = i SynthBrass2
sopranoSax      = i SopranoSax
altoSax         = i AltoSax
tenorSax        = i TenorSax
baritoneSax     = i BaritoneSax
oboe            = i Oboe
bassoon         = i Bassoon
clarinet        = i Clarinet
piccolo         = i Piccolo
fluto           = i Flute
recorder        = i Recorder
panFlute        = i PanFlute
blownBottle     = i BlownBottle
shakuhachi      = i Shakuhachi
whistle         = i Whistle
ocarina         = i Ocarina
lead    1       = i Lead1Square
lead    2       = i Lead2Sawtooth
lead    3       = i Lead3Calliope
lead    4       = i Lead4Chiff
lead    5       = i Lead5Charang
lead    6       = i Lead6Voice
lead    7       = i Lead7Fifths
lead    8       = i Lead8BassLead
pad     1       = i Pad1NewAge
pad     2       = i Pad2Warm
pad     3       = i Pad3Polysynth
pad     4       = i Pad4Choir
pad     5       = i Pad5Bowed
pad     6       = i Pad6Metallic
pad     7       = i Pad7Halo
pad     8       = i Pad8Sweep
fx      1       = i FX1Train
fx      2       = i FX2Soundtrack
fx      3       = i FX3Crystal
fx      4       = i FX4Atmosphere
fx      5       = i FX5Brightness
fx      6       = i FX6Goblins
fx      7       = i FX7Echoes
fx      8       = i FX8SciFi
sitar           = i Sitar
banjo           = i Banjo
shamisen        = i Shamisen
koto            = i Koto
kalimba         = i Kalimba
bagpipe         = i Bagpipe





